language: node_js
node_js:
  - lts/*
install:
  - yarn
script:
  - yarn build docs
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: 34aca66b0dd5c17de15a677595b4c4665eba1401
  keep_history: true
  on:
    branch: main
